FROM --platform=$TARGETPLATFORM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    curl \
    zip \
    unzip \
    tar \
    pkg-config

WORKDIR /src
COPY . .

# Initialize vcpkg
RUN git submodule update --init --recursive && \
    ./vcpkg/bootstrap-vcpkg.sh && \
    ./vcpkg/vcpkg integrate install

# Build
RUN make release

FROM scratch AS export
COPY --from=builder /src/build/release/flapi /build/release/flapi