version: '3.8'

services:
  flapi:
    image: ghcr.io/datazoode/flapi:latest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/creds/service-account.json
    ports:
      - 8080:8080
    command: --config /app/examples/flapi.yaml
    volumes:
      - ../../examples:/app/examples
      # Mount GCP service account json file from host machine
      - $HOME/.gcp/sa-dbt-master.json:/creds/service-account.json
