FORMAT: 1A
HOST: http://localhost:8080

# example-flapi-project

An example flAPI project demonstrating various configuration options

# Group Customers

## GET /customers/
+ Response 200 (application/json)
    + Attributes (object)
        + data (array[Customer])
        + next: "/customers/?offset=100&limit=100" (string)
        + total_count: 1500 (number)

## GET /customers/?{id}
+ Parameters
    + id: 123 (string, optional) - Customer ID 

+ Response 200 (application/json)

    {
        "data": [
            {
                "c_acctbal": 5897.83,
                "c_address": "YsOnaaER8MkvK5cpf4VSlq",
                "c_comment": "ependencies. regular, ironic requests are fluffily regu",
                "c_custkey": 123,
                "c_mktsegment": "BUILDING",
                "c_name": "Customer#000000123",
                "c_nationkey": 5,
                "c_phone": "15-817-151-1168"
            }
        ],
        "next": "",
        "total_count": 1
    }


# Data Structures

## Customer (object)
+ c_custkey: (number) - Customer key
+ c_name: (string) - Customer name
+ c_address: (string) - Customer address
+ c_nationkey: (number) - Customer nation key
+ c_phone: (string) - Customer phone number
+ c_acctbal: (number) - Customer account balance
+ c_mktsegment: (string) - Customer market segment
+ c_comment: (string) - Customer comment
